on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Docker hub login"
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_LOGIN}}
      
      - name: "Image build"
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/FirstImage .

      - name: "Push to docker hub"
        run: docker push ${{secrets.DOCKER_USERNAME}}/FirstImage

